configName: pic32cm_mc00_curiosity_pro
folderName: ''
format_version: v1.0
frameworkPath: ../../../../..
processor: PIC32CM1216MC00048
projectName: ''
settings:
  PackageFilter: aerospace;aws_cloud;azure-rtos-threadx;bootloader;bootloader_apps_uart;bsp;core;crypto;cryptoauthlib;csp;expresslogic_threadx;gfx;gfx_apps;micrium_ucos3;net;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-MC_DFP\1.2.48\PIC32CM1216MC00048\atdf\PIC32CM1216MC00048.atdf
