format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32CM_MC_Curiosity_Pro, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '214', y: '102', id: BSP_PIC32CM_MC_Curiosity_Pro}
